// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0GqkJUa9j1xh-ABwcRGtd_lMUio0SR5Q',
    appId: '1:699799541574:web:2979386f0888245fa8f747',
    messagingSenderId: '699799541574',
    projectId: 'flutterbook-90a12',
    authDomain: 'flutterbook-90a12.firebaseapp.com',
    storageBucket: 'flutterbook-90a12.appspot.com',
    measurementId: 'G-PMN5L8SBX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH7HD9mfMTA-bmGrwDeoHE-MHoM6yRrGs',
    appId: '1:699799541574:android:d98f934edbb12e91a8f747',
    messagingSenderId: '699799541574',
    projectId: 'flutterbook-90a12',
    storageBucket: 'flutterbook-90a12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0iiGzm_2EOGZ6sdYHogijFarY_VRx8mM',
    appId: '1:699799541574:ios:4071a8b923d70d33a8f747',
    messagingSenderId: '699799541574',
    projectId: 'flutterbook-90a12',
    storageBucket: 'flutterbook-90a12.appspot.com',
    iosClientId: '699799541574-f0oc1u2ns3s62gvn5u6ibupkmdas8g16.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0iiGzm_2EOGZ6sdYHogijFarY_VRx8mM',
    appId: '1:699799541574:ios:fbeaa9a07011d3f5a8f747',
    messagingSenderId: '699799541574',
    projectId: 'flutterbook-90a12',
    storageBucket: 'flutterbook-90a12.appspot.com',
    iosClientId: '699799541574-ji8qp6l182ba390jp59qo4iebsi5tgee.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBook.RunnerTests',
  );
}
